package com.yagay.suite.core

import android.content.Context
import android.content.Intent

/**
 * Minimal registration contract for one reusable feature.
 *
 * Keep feature-specific business logic out of this class. A feature must remain independently
 * buildable while exposing the same entry/runtime implementation to YSuite.
 */
data class FeatureSpec(
    val id: String,
    val name: String,
    val description: String,
    val entryActivityClassName: String,
    val runtimeInitializerClassName: String? = null,
    /** Shared host capabilities consumed by this feature when embedded in YSuite. */
    val sharedCapabilities: Set<SuiteCapability> = emptySet(),
    /**
     * Optional standalone-safe bridge consumed by YSuite's one AccessibilityService.
     *
     * The class is loaded reflectively so a feature does not depend on YSuite/core. It may expose
     * public static onServiceConnected(Context), onServiceDisconnected(Context), and
     * onAccessibilityEvent(Context, AccessibilityEvent) methods.
     */
    val accessibilityBridgeClassName: String? = null,
    /**
     * Optional standalone-safe bridge consumed by YSuite's one NotificationListenerService.
     *
     * It may expose public static callback methods accepting NotificationListenerService and the
     * platform callback arguments. The feature therefore shares the host grant without depending
     * on YSuite/core and remains independently buildable.
     */
    val notificationListenerBridgeClassName: String? = null,
    /**
     * Optional standalone BroadcastReceiver implementation used as a logical lifecycle handler
     * inside YSuite. The receiver class is not registered with Android in the combined host;
     * YSuite's one SuiteBootReceiver instantiates it and dispatches supported system events.
     */
    val bootReceiverClassName: String? = null,
    /** Logical exported IPC receiver handlers. Android registers only SuiteBridgeReceiver. */
    val ipcReceiverClassNames: Set<String> = emptySet(),
    val requiresRoot: Boolean = false,
    val requiresHook: Boolean = false,
    val defaultEnabled: Boolean = true,
) {
    fun isIncluded(): Boolean = runCatching { Class.forName(entryActivityClassName) }.isSuccess

    fun createIntent(context: Context): Intent = Intent(context, Class.forName(entryActivityClassName))

    /** All host-side runtime activation passes through the shared lifecycle owner. */
    fun initialize(context: Context): Any? = FeatureRuntimeManager.enable(context, this).getOrThrow()

    /** Reflective runtime factory used only by [FeatureRuntimeManager]. */
    internal fun instantiateRuntime(context: Context): Any? {
        val className = runtimeInitializerClassName ?: return null
        val runtimeClass = Class.forName(className)
        return runtimeClass.getMethod("get", Context::class.java).invoke(null, context.applicationContext)
    }
}

/**
 * Runtime view of config/features.toml.
 *
 * Do not add FeatureSpec entries here. The checked-in GeneratedFeatureCatalog is regenerated by
 * tools/generate_feature_catalog.py and CI rejects stale generated files.
 */
object FeatureRegistry {
    val all: List<FeatureSpec> = GeneratedFeatureCatalog.all

    fun included(): List<FeatureSpec> = all.filter(FeatureSpec::isIncluded)
}

class FeatureStateStore(context: Context) {
    private val appContext = context.applicationContext
    private val prefs = appContext.getSharedPreferences(
        SuiteContract.FEATURE_STATE_PREFS,
        Context.MODE_PRIVATE,
    )

    fun isEnabled(feature: FeatureSpec): Boolean =
        prefs.getBoolean(SuiteContract.FEATURE_STATE_KEY_PREFIX + feature.id, feature.defaultEnabled)

    /**
     * The persisted switch is the authoritative feature state for the combined host.
     *
     * Enable ordering matters: the managed runtime is made ready before LSPosed replays an existing
     * service connection. Disable ordering is the inverse: Hook/service callbacks and Root work are
     * cut off first, then the feature gets its cleanup callback. This prevents callbacks racing a
     * stopped runtime while still keeping the persisted switch as the source of truth.
     */
    fun setEnabled(feature: FeatureSpec, enabled: Boolean) {
        prefs.edit()
            .putBoolean(SuiteContract.FEATURE_STATE_KEY_PREFIX + feature.id, enabled)
            .apply()

        val lifecycle = if (enabled) {
            FeatureRuntimeManager.enable(appContext, feature).map { Unit }.also { result ->
                if (result.isSuccess) {
                    SuiteXposedServiceBroker.setPluginEnabled(feature.id, true)
                } else {
                    // Do not leave Hook/Root-facing state enabled when runtime activation failed.
                    prefs.edit()
                        .putBoolean(SuiteContract.FEATURE_STATE_KEY_PREFIX + feature.id, false)
                        .apply()
                    SuiteXposedServiceBroker.setPluginEnabled(feature.id, false)
                }
            }
        } else {
            SuiteXposedServiceBroker.setPluginEnabled(feature.id, false)
            SuiteRootGateway.stopPluginProcesses(feature.id)
            FeatureRuntimeManager.disable(appContext, feature)
        }

        lifecycle.onFailure {
            SuiteLog.e(
                appContext,
                feature.id,
                if (enabled) "host enable failed" else "host disable failed",
                it,
            )
        }
    }
}
