package com.yagay.ysuite.feature.ynotify.api

enum class YNotifyEventType {
    Notification,
    Toast,
    Dialog,
    Snackbar,
    Popup,
    SystemUi,
    OtherUi,
}

enum class YNotifyNotificationKind {
    FullScreen,
    Bubble,
    Call,
    Alarm,
    Media,
    Progress,
    ForegroundService,
    Message,
    System,
    Ongoing,
    Silent,
    Standard,
    Unknown,
}

data class YNotifyEvent(
    val id: Long,
    val eventKey: String,
    val eventType: YNotifyEventType,
    val source: String,
    val packageName: String,
    val appLabel: String,
    val title: String?,
    val text: String?,
    val fullText: String?,
    val subText: String? = null,
    val summaryText: String? = null,
    val rawExtras: String? = null,
    val messagesJson: String? = null,
    val actionsJson: String? = null,
    val postedAt: Long,
    val updatedAt: Long,
    val removedAt: Long?,
    val notificationKey: String?,
    val notificationId: Int = 0,
    val notificationTag: String? = null,
    val channelId: String? = null,
    val channelName: String? = null,
    val channelDescription: String? = null,
    val channelImportance: Int = 0,
    val groupKey: String? = null,
    val groupSummary: Boolean = false,
    val category: String? = null,
    val template: String? = null,
    val importance: Int = 0,
    val conversation: Boolean = false,
    val rankingCanBubble: Boolean = false,
    val rankingAmbient: Boolean = false,
    val rankingSuspended: Boolean = false,
    val flags: Int = 0,
    val clearable: Boolean = true,
    val bubble: Boolean = false,
    val fullScreen: Boolean = false,
    val payloadSilent: Boolean = false,
    val silent: Boolean = false,
    val removalReason: Int = 0,
    val notificationKind: YNotifyNotificationKind,
    val headsUp: Boolean,
    val bubbleShown: Boolean,
    val fullScreenShown: Boolean,
    val ongoing: Boolean,
    val foregroundService: Boolean,
    val progress: Int,
    val progressMax: Int,
    val progressIndeterminate: Boolean,
    val className: String?,
    val classificationVersion: Int,
    val classificationLocked: Boolean = false,
    val originalEventType: YNotifyEventType? = null,
    val classificationSource: String? = null,
    val mergedIntoId: Long? = null,
)

data class YNotifyRuntimeStatus(
    val notificationListenerConnected: Boolean,
    val accessibilityConnected: Boolean,
    val storedEventCount: Int,
    val lastReceivedAt: Long = 0L,
    val lastSavedAt: Long = 0L,
    val lastPackage: String? = null,
    val lastError: String? = null,
)
