package com.yagay.ysuite.feature.yparam.api

data class YParamAppSummary(
    val packageName: String,
    val label: String,
    val system: Boolean,
    val enabled: Boolean,
    val overrideCount: Int,
)

data class YParamOverrides(
    val densityDpi: Int? = null,
    val widthPixels: Int? = null,
    val heightPixels: Int? = null,
    val smallestWidthDp: Int? = null,
    val screenWidthDp: Int? = null,
    val screenHeightDp: Int? = null,
    val fontScale: Float? = null,
    val xdpi: Float? = null,
    val ydpi: Float? = null,
    val refreshRate: Float? = null,
    val localeTag: String? = null,
    val timeZoneId: String? = null,
    val nightMode: String? = null,
    val orientation: String? = null,
    val userAgent: String? = null,
    val allowScreenshots: Boolean? = null,
    val keepScreenOn: Boolean? = null,
    val locationMode: String? = null,
    val latitude: Double? = null,
    val longitude: Double? = null,
    val altitude: Double? = null,
    val accuracy: Float? = null,
    val speed: Float? = null,
    val bearing: Float? = null,
    val randomRadiusMeters: Float? = null,
    val locationUpdateIntervalMs: Int? = null,
) {
    fun overrideCount(): Int =
        listOf(
            densityDpi,
            widthPixels,
            heightPixels,
            smallestWidthDp,
            screenWidthDp,
            screenHeightDp,
            fontScale,
            xdpi,
            ydpi,
            refreshRate,
            localeTag,
            timeZoneId,
            nightMode,
            orientation,
            userAgent,
            allowScreenshots,
            keepScreenOn,
            locationMode,
            latitude,
            longitude,
            altitude,
            accuracy,
            speed,
            bearing,
            randomRadiusMeters,
            locationUpdateIntervalMs,
        ).count { it != null }
}

data class YParamDefaults(
    val densityDpi: Int,
    val widthPixels: Int,
    val heightPixels: Int,
    val smallestWidthDp: Int,
    val screenWidthDp: Int,
    val screenHeightDp: Int,
    val fontScale: Float,
    val xdpi: Float,
    val ydpi: Float,
    val refreshRate: Float?,
    val localeTag: String,
    val timeZoneId: String,
    val nightMode: String,
    val orientation: String,
)
