package com.yagay.YSuite.xposed;

// Generated from config/features.toml by tools/generate_feature_catalog.py.
// Do not edit this file directly.
final class GeneratedXposedPlugins {
    private GeneratedXposedPlugins() {}

    static final Entry[] ENTRIES = {
            new Entry("yentrycleaner/main", "com.yagay.YEntryCleaner.xposed.YEntryCleanerModule"),
            new Entry("yentrycleaner/state", "com.yagay.YEntryCleaner.xposed.ComponentStateGuardModule"),
            new Entry("yentrycleaner/discovery", "com.yagay.YEntryCleaner.xposed.ComponentDiscoveryFilterModule"),
            new Entry("yentrycleaner/probe", "com.yagay.YEntryCleaner.xposed.SuiteRuntimeProbeBridgeModule"),
            new Entry("ydiag/main", "com.yagay.ydiag.xposed.YDiagModule"),
            new Entry("ynotify/main", "com.yagay.YNotify.xposed.YNotifyModule"),
            new Entry("ypower/main", "com.yagay.ypower.hook.YPowerModule"),
            new Entry("ypower/security", "com.yagay.ypower.hook.SupplementalSecurityModule"),
            new Entry("ypower/observation", "com.yagay.ypower.hook.DeepObservationModule"),
            new Entry("yminiguard/main", "com.yagay.YMiniGuard.GuardModule"),
            new Entry("ynfc/main", "com.yagay.YNFC.xposed.NfcInjectionModule"),
            new Entry("ytaskmanager/main", "com.yagay.YTaskManager.xposed.TaskManagerModule"),
            new Entry("yparam/main", "com.yagay.yparam.hook.YParamModule"),
            new Entry("yfloat/main", "com.yagay.YFloat.hook.YFloatModule"),
    };

    record Entry(String id, String entryClassName) {}
}
