plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.compose) apply false
    alias(libs.plugins.kotlin.serialization) apply false
}

def localSuiteShared = rootProject.findProject(':ysuite-api') != null &&
        rootProject.findProject(':ysuite-ui') != null

if (localSuiteShared) {
    subprojects {
        configurations.configureEach {
            resolutionStrategy.dependencySubstitution {
                substitute(module('com.github.yagay.YSuite:api')).using(project(':ysuite-api'))
                substitute(module('com.github.yagay.YSuite:ui')).using(project(':ysuite-ui'))
            }
        }
    }
}
