// Generated by tools/generate_yui_tokens.py. Do not edit manually.
package com.yagay.yui

import androidx.compose.ui.unit.dp

/** Canonical geometry generated from libs/yui/yui_tokens.json. */
object YDimens {
    val ScreenHorizontal = 12.dp
    val ScreenHorizontalMedium = 18.dp
    val ScreenHorizontalExpanded = 24.dp
    val ScreenVertical = 8.dp
    val SectionGap = 10.dp
    val CardPadding = 10.dp
    val ControlGap = 8.dp
    val ToolbarHeight = 52.dp
    val ButtonHeight = 48.dp
    val TouchTarget = 48.dp
    val CardRadius = 12.dp
    val CompactBreakpoint = 420.dp
    val MediumBreakpoint = 600.dp
    val ExpandedBreakpoint = 840.dp
    val ContentMaxWidth = 1280.dp
    val FormMaxWidth = 840.dp
    val ListDetailListWidth = 360.dp
    val NavigationRailWidth = 80.dp
    val PaneGap = 12.dp
    val ButtonVisualHeight = 40.dp
    val ButtonPaddingHorizontal = 10.dp
    val ButtonPaddingVertical = 2.dp
    val ButtonInsetVertical = 4.dp
    val ButtonTextPaddingHorizontal = 8.dp
    val ButtonRadius = 8.dp
    val OptionRowHeight = 48.dp
    val SwitchTrackWidth = 38.dp
    val SwitchTrackHeight = 22.dp
    val SwitchThumbSize = 18.dp
    val SwitchSlotWidth = 52.dp
    val SwitchSlotHeight = 40.dp
    val SpacingXsmall = 4.dp
    val SpacingSmall = 6.dp
    val SpacingMedium = 12.dp
    val SpacingLarge = 16.dp
    val SpacingXlarge = 24.dp
}
