// Generated by tools/generate_yui_tokens.py. Do not edit manually.
package com.yagay.yui

import androidx.compose.ui.unit.dp

/** Canonical geometry generated from libs/yui/yui_tokens.json. */
object YDimens {
    val ScreenHorizontal = 16.dp
    val ScreenHorizontalMedium = 24.dp
    val ScreenHorizontalExpanded = 32.dp
    val ScreenVertical = 12.dp
    val SectionGap = 16.dp
    val CardPadding = 16.dp
    val ControlGap = 12.dp
    val ToolbarHeight = 64.dp
    val ButtonHeight = 48.dp
    val TouchTarget = 48.dp
    val CardRadius = 16.dp
    val CompactBreakpoint = 420.dp
    val MediumBreakpoint = 600.dp
    val ExpandedBreakpoint = 840.dp
    val ContentMaxWidth = 1280.dp
    val FormMaxWidth = 840.dp
    val ListDetailListWidth = 360.dp
    val NavigationRailWidth = 80.dp
    val PaneGap = 16.dp
    val ButtonVisualHeight = 48.dp
    val ButtonPaddingHorizontal = 24.dp
    val ButtonPaddingVertical = 8.dp
    val ButtonInsetVertical = 0.dp
    val ButtonTextPaddingHorizontal = 16.dp
    val ButtonRadius = 24.dp
    val OptionRowHeight = 56.dp
    val ListIconSize = 48.dp
    val IconVisualSize = 24.dp
    val IconSmallSize = 16.dp
    val SwitchTrackWidth = 52.dp
    val SwitchTrackHeight = 32.dp
    val SwitchThumbSize = 24.dp
    val SwitchSlotWidth = 56.dp
    val SwitchSlotHeight = 48.dp
    val SpacingXsmall = 4.dp
    val SpacingSmall = 8.dp
    val SpacingMedium = 16.dp
    val SpacingLarge = 24.dp
    val SpacingXlarge = 32.dp
}
