# id|impl module|registration class|application id
template|:feature:template:impl|com.yagay.ysuite.feature.template.TemplateFeatureUiRegistration|com.yagay.ysuite.template.standalone
settings|:feature:settings:impl|com.yagay.ysuite.feature.settings.SettingsStandaloneFeatureUiRegistration|com.yagay.ysuite.settings.standalone
yfiles|:feature:yfiles:impl|com.yagay.ysuite.feature.yfiles.YFilesStandaloneFeatureUiRegistration|com.yagay.ysuite.yfiles.standalone
ydownload|:feature:ydownload:impl|com.yagay.ysuite.feature.ydownload.YDownloadStandaloneFeatureUiRegistration|com.yagay.ysuite.ydownload.standalone
ytaskmanager|:feature:ytaskmanager:impl|com.yagay.ysuite.feature.ytaskmanager.YTaskManagerStandaloneFeatureUiRegistration|com.yagay.ysuite.ytaskmanager.standalone
yparam|:feature:yparam:impl|com.yagay.ysuite.feature.yparam.YParamStandaloneFeatureUiRegistration|com.yagay.ysuite.yparam.standalone
ydiag|:feature:ydiag:impl|com.yagay.ysuite.feature.ydiag.YDiagStandaloneFeatureUiRegistration|com.yagay.ysuite.ydiag.standalone
ypower|:feature:ypower:impl|com.yagay.ysuite.feature.ypower.YPowerStandaloneFeatureUiRegistration|com.yagay.ysuite.ypower.standalone
ynotify|:feature:ynotify:impl|com.yagay.ysuite.feature.ynotify.YNotifyStandaloneFeatureUiRegistration|com.yagay.ysuite.ynotify.standalone
ynfc|:feature:ynfc:impl|com.yagay.ysuite.feature.ynfc.YNfcStandaloneFeatureUiRegistration|com.yagay.ysuite.ynfc.standalone
