#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "libs/yui/yui_tokens.json"
KOTLIN = ROOT / "libs/yui/src/main/java/com/yagay/yui/YGeneratedTokens.kt"
XML = ROOT / "libs/yui/src/main/res/values/yui_tokens.xml"
PALETTE_SOURCE = ROOT / "libs/yui/yui_palette.json"
YUI_PALETTE = ROOT / "libs/yui/src/main/java/com/yagay/yui/YUiPalette.kt"
LIGHT_XML = ROOT / "libs/yui/src/main/res/values/yui_palette.xml"
DARK_XML = ROOT / "libs/yui/src/main/res/values-night/yui_palette.xml"

TOKENS = [
    ("screen_horizontal", "ScreenHorizontal"),
    ("screen_horizontal_medium", "ScreenHorizontalMedium"),
    ("screen_horizontal_expanded", "ScreenHorizontalExpanded"),
    ("screen_vertical", "ScreenVertical"),
    ("section_gap", "SectionGap"),
    ("card_padding", "CardPadding"),
    ("control_gap", "ControlGap"),
    ("toolbar_height", "ToolbarHeight"),
    ("button_height", "ButtonHeight"),
    ("touch_target", "TouchTarget"),
    ("card_radius", "CardRadius"),
    ("compact_breakpoint", "CompactBreakpoint"),
    ("medium_breakpoint", "MediumBreakpoint"),
    ("expanded_breakpoint", "ExpandedBreakpoint"),
    ("content_max_width", "ContentMaxWidth"),
    ("form_max_width", "FormMaxWidth"),
    ("list_detail_list_width", "ListDetailListWidth"),
    ("navigation_rail_width", "NavigationRailWidth"),
    ("pane_gap", "PaneGap"),
    ("button_visual_height", "ButtonVisualHeight"),
    ("button_padding_horizontal", "ButtonPaddingHorizontal"),
    ("button_padding_vertical", "ButtonPaddingVertical"),
    ("button_inset_vertical", "ButtonInsetVertical"),
    ("button_text_padding_horizontal", "ButtonTextPaddingHorizontal"),
    ("button_radius", "ButtonRadius"),
    ("option_row_height", "OptionRowHeight"),
    ("switch_track_width", "SwitchTrackWidth"),
    ("switch_track_height", "SwitchTrackHeight"),
    ("switch_thumb_size", "SwitchThumbSize"),
    ("switch_slot_width", "SwitchSlotWidth"),
    ("switch_slot_height", "SwitchSlotHeight"),
    ("spacing_xsmall", "SpacingXsmall"),
    ("spacing_small", "SpacingSmall"),
    ("spacing_medium", "SpacingMedium"),
    ("spacing_large", "SpacingLarge"),
    ("spacing_xlarge", "SpacingXlarge"),
]


def read_source() -> dict[str, int]:
    raw = json.loads(SOURCE.read_text(encoding="utf-8"))
    expected = {name for name, _ in TOKENS}
    missing = sorted(expected - set(raw))
    extra = sorted(set(raw) - expected)
    if missing or extra:
        raise SystemExit(f"yui-tokens: invalid keys missing={missing} extra={extra}")
    values: dict[str, int] = {}
    for key, _ in TOKENS:
        value = raw[key]
        if not isinstance(value, int) or value <= 0:
            raise SystemExit(f"yui-tokens: {key} must be a positive integer dp value")
        values[key] = value
    return values


def kotlin_content(values: dict[str, int]) -> str:
    rows = "\n".join(f"    val {kt} = {values[key]}.dp" for key, kt in TOKENS)
    return (
        "// Generated by tools/generate_yui_tokens.py. Do not edit manually.\n"
        "package com.yagay.yui\n\n"
        "import androidx.compose.ui.unit.dp\n\n"
        "/** Canonical geometry generated from libs/yui/yui_tokens.json. */\n"
        "object YDimens {\n"
        f"{rows}\n"
        "}\n"
    )


def xml_content(values: dict[str, int]) -> str:
    rows = "\n".join(f"    <dimen name=\"yui_{key}\">{values[key]}dp</dimen>" for key, _ in TOKENS)
    return (
        "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
        "<!-- Generated by tools/generate_yui_tokens.py. Do not edit manually. -->\n"
        "<resources>\n"
        f"{rows}\n"
        "</resources>\n"
    )



def read_palette() -> dict[str, dict[str, str]]:
    raw = json.loads(PALETTE_SOURCE.read_text(encoding="utf-8"))
    if set(raw) != {"light", "dark"} or not isinstance(raw["light"], dict) or not isinstance(raw["dark"], dict):
        raise SystemExit("yui-palette: expected light/dark color dictionaries")
    if not raw["light"] or set(raw["light"]) != set(raw["dark"]):
        raise SystemExit("yui-palette: light and dark roles must match")
    for scheme in ("light", "dark"):
        for role, value in raw[scheme].items():
            if not re.fullmatch(r"[a-z][a-zA-Z0-9]*", role):
                raise SystemExit(f"yui-palette: invalid role {role!r}")
            if not isinstance(value, str) or not re.fullmatch(r"#[0-9A-Fa-f]{6}", value):
                raise SystemExit(f"yui-palette: invalid color {scheme}.{role}")
    return raw


def palette_kotlin_content(colors: dict[str, dict[str, str]], package: str) -> str:
    roles = sorted(colors["light"])
    rows = "\n".join(
        f"    val {scheme.title()}{role[0].upper()}{role[1:]} = Color(0xFF{colors[scheme][role][1:]})"
        for scheme in ("light", "dark")
        for role in roles
    )
    return (
        "// Generated by tools/generate_yui_tokens.py. Do not edit manually.\n"
        f"package {package}\n\n"
        "import androidx.compose.ui.graphics.Color\n\n"
        "/** Shared static light/dark palette; dynamic system colors still take precedence. */\n"
        "object YUiPalette {\n"
        f"{rows}\n"
        "}\n"
    )


def palette_xml_content(colors: dict[str, dict[str, str]], scheme: str) -> str:
    roles = sorted(colors["light"])
    rows = "\n".join(
        '    <color name="yui_palette_{}">{}</color>'.format(
            re.sub(r"(?<!^)(?=[A-Z])", "_", role).lower(), colors[scheme][role]
        )
        for role in roles
    )
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Generated by tools/generate_yui_tokens.py. Do not edit manually. -->\n"
        "<resources>\n"
        f"{rows}\n"
        "</resources>\n"
    )


def check_or_write(path: Path, expected: str, check: bool) -> None:
    if check:
        actual = path.read_text(encoding="utf-8") if path.is_file() else ""
        if actual != expected:
            raise SystemExit(f"yui-tokens: generated file is stale: {path.relative_to(ROOT)}")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    values = read_source()
    check_or_write(KOTLIN, kotlin_content(values), args.check)
    check_or_write(XML, xml_content(values), args.check)
    colors = read_palette()
    check_or_write(YUI_PALETTE, palette_kotlin_content(colors, "com.yagay.yui"), args.check)
    check_or_write(LIGHT_XML, palette_xml_content(colors, "light"), args.check)
    check_or_write(DARK_XML, palette_xml_content(colors, "dark"), args.check)
    mode = "OK" if args.check else "generated"
    print(f"yui-tokens: {mode} dimensions={len(TOKENS)} colors={len(colors['light'])}")


if __name__ == "__main__":
    main()
