#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "libs/yui/yui_tokens.json"
KOTLIN = ROOT / "libs/yui/src/main/java/com/yagay/yui/YGeneratedTokens.kt"
XML = ROOT / "libs/yui/src/main/res/values/yui_tokens.xml"

TOKENS = [
    ("screen_horizontal", "ScreenHorizontal"),
    ("screen_vertical", "ScreenVertical"),
    ("section_gap", "SectionGap"),
    ("card_padding", "CardPadding"),
    ("control_gap", "ControlGap"),
    ("toolbar_height", "ToolbarHeight"),
    ("button_height", "ButtonHeight"),
    ("touch_target", "TouchTarget"),
    ("card_radius", "CardRadius"),
    ("compact_breakpoint", "CompactBreakpoint"),
    ("medium_breakpoint", "MediumBreakpoint"),
    ("expanded_breakpoint", "ExpandedBreakpoint"),
    ("content_max_width", "ContentMaxWidth"),
    ("form_max_width", "FormMaxWidth"),
    ("list_detail_list_width", "ListDetailListWidth"),
    ("navigation_rail_width", "NavigationRailWidth"),
    ("pane_gap", "PaneGap"),
]


def read_source() -> dict[str, int]:
    raw = json.loads(SOURCE.read_text(encoding="utf-8"))
    expected = {name for name, _ in TOKENS}
    missing = sorted(expected - set(raw))
    extra = sorted(set(raw) - expected)
    if missing or extra:
        raise SystemExit(f"yui-tokens: invalid keys missing={missing} extra={extra}")
    values: dict[str, int] = {}
    for key, _ in TOKENS:
        value = raw[key]
        if not isinstance(value, int) or value <= 0:
            raise SystemExit(f"yui-tokens: {key} must be a positive integer dp value")
        values[key] = value
    return values


def kotlin_content(values: dict[str, int]) -> str:
    rows = "\n".join(f"    val {kt} = {values[key]}.dp" for key, kt in TOKENS)
    return (
        "// Generated by tools/generate_yui_tokens.py. Do not edit manually.\n"
        "package com.yagay.yui\n\n"
        "import androidx.compose.ui.unit.dp\n\n"
        "/** Canonical geometry generated from libs/yui/yui_tokens.json. */\n"
        "object YDimens {\n"
        f"{rows}\n"
        "}\n"
    )


def xml_content(values: dict[str, int]) -> str:
    rows = "\n".join(f"    <dimen name=\"yui_{key}\">{values[key]}dp</dimen>" for key, _ in TOKENS)
    return (
        "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
        "<!-- Generated by tools/generate_yui_tokens.py. Do not edit manually. -->\n"
        "<resources>\n"
        f"{rows}\n"
        "</resources>\n"
    )


def check_or_write(path: Path, expected: str, check: bool) -> None:
    if check:
        actual = path.read_text(encoding="utf-8") if path.is_file() else ""
        if actual != expected:
            raise SystemExit(f"yui-tokens: generated file is stale: {path.relative_to(ROOT)}")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    values = read_source()
    check_or_write(KOTLIN, kotlin_content(values), args.check)
    check_or_write(XML, xml_content(values), args.check)
    mode = "OK" if args.check else "generated"
    print(f"yui-tokens: {mode} tokens={len(TOKENS)}")


if __name__ == "__main__":
    main()
