#!/usr/bin/env python3
from __future__ import annotations

import argparse
import difflib
import json
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "config/features.toml"
GENERATED_FEATURES = ROOT / "libs/ycore/src/main/java/com/yagay/suite/core/GeneratedFeatureCatalog.kt"
GENERATED_HOOKS = ROOT / "suite/YSuite/src/main/java/com/yagay/YSuite/xposed/GeneratedXposedPlugins.java"
GENERATED_MODULES = ROOT / "config/generated/feature-modules.tsv"

ALLOWED_CAPABILITIES = {
    "ROOT",
    "LSPOSED",
    "ACCESSIBILITY",
    "NOTIFICATION_LISTENER",
    "OVERLAY",
    "NOTIFICATIONS",
}


def fail(message: str) -> None:
    print(f"feature-generator: ERROR: {message}", file=sys.stderr)
    raise SystemExit(1)


def q(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def load_features() -> list[dict]:
    data = tomllib.loads(CATALOG.read_text(encoding="utf-8"))
    if data.get("schema") != 2:
        fail("config/features.toml must use schema = 2")
    features = data.get("feature") or []
    if not features:
        fail("catalog has no [[feature]] entries")

    ids: set[str] = set()
    modules: set[str] = set()
    project_dirs: set[str] = set()
    hook_ids: set[str] = set()
    for item in features:
        for key in ("id", "name", "description", "gradle_module", "project_dir", "entry_activity"):
            if not str(item.get(key, "")).strip():
                fail(f"feature is missing required field {key}: {item!r}")
        feature_id = item["id"]
        if feature_id in ids:
            fail(f"duplicate feature id: {feature_id}")
        ids.add(feature_id)

        module = item["gradle_module"]
        if not module.startswith(":"):
            fail(f"{feature_id}: gradle_module must start with ':'")
        if module in modules:
            fail(f"duplicate gradle_module: {module}")
        modules.add(module)

        project_dir = item["project_dir"]
        if project_dir in project_dirs:
            fail(f"duplicate project_dir: {project_dir}")
        project_dirs.add(project_dir)

        lifecycle = item.get("lifecycle", "legacy")
        if lifecycle not in {"legacy", "managed"}:
            fail(f"{feature_id}: lifecycle must be legacy or managed")

        capabilities = set(item.get("capabilities") or [])
        unknown = capabilities - ALLOWED_CAPABILITIES
        if unknown:
            fail(f"{feature_id}: unknown capabilities: {sorted(unknown)}")

        for hook in item.get("hooks") or []:
            hook_id = str(hook.get("id", ""))
            hook_class = str(hook.get("class", ""))
            if not hook_id or not hook_class:
                fail(f"{feature_id}: every hook requires id and class")
            if not hook_id.startswith(feature_id + "/"):
                fail(f"{feature_id}: hook id must be namespaced: {hook_id}")
            if hook_id in hook_ids:
                fail(f"duplicate hook id: {hook_id}")
            hook_ids.add(hook_id)
    return features


def render_feature_catalog(features: list[dict]) -> str:
    lines = [
        "package com.yagay.suite.core",
        "",
        "// Generated from config/features.toml by tools/generate_feature_catalog.py.",
        "// Do not edit this file directly.",
        "internal object GeneratedFeatureCatalog {",
        "    val all: List<FeatureSpec> = listOf(",
    ]
    for item in features:
        caps = item.get("capabilities") or []
        hooks = item.get("hooks") or []
        cap_expr = "emptySet()" if not caps else "setOf(" + ", ".join(
            f"SuiteCapability.{cap}" for cap in caps
        ) + ")"
        ipc = item.get("ipc_receivers") or []
        ipc_expr = "emptySet()" if not ipc else "setOf(" + ", ".join(q(value) for value in ipc) + ")"
        runtime = item.get("runtime")
        accessibility = item.get("accessibility_bridge")
        notification = item.get("notification_listener_bridge")
        boot = item.get("boot_receiver")
        lines.extend([
            "        FeatureSpec(",
            f"            id = {q(item['id'])},",
            f"            name = {q(item['name'])},",
            f"            description = {q(item['description'])},",
            f"            entryActivityClassName = {q(item['entry_activity'])},",
            f"            runtimeInitializerClassName = {q(runtime) if runtime else 'null'},",
            f"            sharedCapabilities = {cap_expr},",
            f"            accessibilityBridgeClassName = {q(accessibility) if accessibility else 'null'},",
            f"            notificationListenerBridgeClassName = {q(notification) if notification else 'null'},",
            f"            bootReceiverClassName = {q(boot) if boot else 'null'},",
            f"            ipcReceiverClassNames = {ipc_expr},",
            f"            requiresRoot = {'true' if 'ROOT' in caps else 'false'},",
            f"            requiresHook = {'true' if hooks else 'false'},",
            f"            defaultEnabled = {'true' if item.get('default_enabled', True) else 'false'},",
            "        ),",
        ])
    lines.extend(["    )", "}", ""])
    return "\n".join(lines)


def render_xposed_plugins(features: list[dict]) -> str:
    lines = [
        "package com.yagay.YSuite.xposed;",
        "",
        "// Generated from config/features.toml by tools/generate_feature_catalog.py.",
        "// Do not edit this file directly.",
        "final class GeneratedXposedPlugins {",
        "    private GeneratedXposedPlugins() {}",
        "",
        "    static final Entry[] ENTRIES = {",
    ]
    for item in features:
        for hook in item.get("hooks") or []:
            lines.append(f"            new Entry({q(hook['id'])}, {q(hook['class'])}),")
    lines.extend([
        "    };",
        "",
        "    record Entry(String id, String entryClassName) {}",
        "}",
        "",
    ])
    return "\n".join(lines)


def render_module_map(features: list[dict]) -> str:
    lines = [
        "# Generated from config/features.toml by tools/generate_feature_catalog.py.",
        "# gradle_module<TAB>project_dir",
    ]
    lines.extend(f"{item['gradle_module']}\t{item['project_dir']}" for item in features)
    lines.append("")
    return "\n".join(lines)


def outputs(features: list[dict]) -> dict[Path, str]:
    return {
        GENERATED_FEATURES: render_feature_catalog(features),
        GENERATED_HOOKS: render_xposed_plugins(features),
        GENERATED_MODULES: render_module_map(features),
    }


def check_file(path: Path, expected: str) -> bool:
    actual = path.read_text(encoding="utf-8") if path.is_file() else ""
    if actual == expected:
        return True
    print(f"feature-generator: stale generated file: {path.relative_to(ROOT)}", file=sys.stderr)
    diff = difflib.unified_diff(
        actual.splitlines(),
        expected.splitlines(),
        fromfile=str(path.relative_to(ROOT)),
        tofile=str(path.relative_to(ROOT)) + " (generated)",
        lineterm="",
    )
    for line in list(diff)[:120]:
        print(line, file=sys.stderr)
    return False


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when generated files are stale")
    args = parser.parse_args()

    features = load_features()
    rendered = outputs(features)
    if args.check:
        ok = all(check_file(path, content) for path, content in rendered.items())
        if not ok:
            raise SystemExit(1)
        print(f"feature-generator: OK features={len(features)} outputs={len(rendered)}")
        return

    for path, content in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"feature-generator: wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
