package com.yagay.ydownload

import android.content.Context
import java.util.concurrent.atomic.AtomicLong
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asStateFlow
import org.json.JSONArray
import org.json.JSONObject

enum class DownloadState { QUEUED, RUNNING, PAUSED, COMPLETED, FAILED, CANCELLED }
enum class DownloadBackend { SYSTEM, ENHANCED }

data class DownloadItem(
    val id: Long,
    val url: String,
    val fileName: String,
    val uri: String? = null,
    val done: Long = 0L,
    val total: Long = -1L,
    val state: DownloadState = DownloadState.QUEUED,
    val error: String? = null,
    val backend: DownloadBackend = DownloadBackend.SYSTEM,
    val systemId: Long? = null,
    /** True when the name came from the URL/fallback and may be refined from HTTP metadata. */
    val autoFileName: Boolean = false,
    /** Safe per-task HTTP request headers. Reserved transport headers are filtered before storage. */
    val requestHeaders: Map<String, String> = emptyMap(),
    /** Optional expected SHA-256 used by the enhanced engine as a hard integrity check. */
    val expectedSha256: String? = null,
    /** Number of automatic retries already consumed by the enhanced engine. */
    val retryCount: Int = 0,
    /** HTTP validator used by the enhanced engine for safe If-Range resume. */
    val etag: String? = null,
    /** Fallback HTTP validator used when a server does not provide ETag. */
    val lastModified: String? = null,
    /** Optional integrity fingerprint calculated after an enhanced download completes. */
    val sha256: String? = null,
    // Runtime-only telemetry. It is deliberately not persisted so stale speed/ETA values are never
    // restored after a process restart.
    val speedBytesPerSecond: Long = 0L,
    val etaMillis: Long = -1L,
)

class DownloadStore private constructor(context: Context) {
    private val prefs = context.applicationContext.getSharedPreferences("ydownload", Context.MODE_PRIVATE)
    private val _items = MutableStateFlow(load())
    val items = _items.asStateFlow()

    @Synchronized
    fun add(
        url: String,
        fileName: String,
        backend: DownloadBackend = DownloadBackend.SYSTEM,
        requestHeaders: Map<String, String> = emptyMap(),
        expectedSha256: String? = null,
    ): DownloadItem {
        val now = System.currentTimeMillis()
        val id = nextId.updateAndGet { previous -> maxOf(previous + 1L, now) }
        val item = DownloadItem(
            id = id,
            url = url,
            fileName = fileName,
            backend = backend,
            autoFileName = looksAutoGenerated(url, fileName),
            requestHeaders = requestHeaders,
            expectedSha256 = expectedSha256,
        )
        save(listOf(item) + _items.value)
        return item
    }

    @Synchronized fun get(id: Long): DownloadItem? = _items.value.firstOrNull { it.id == id }

    @Synchronized fun update(id: Long, block: (DownloadItem) -> DownloadItem): DownloadItem? {
        var updated: DownloadItem? = null
        save(_items.value.map { if (it.id == id) block(it).also { value -> updated = value } else it })
        return updated
    }

    @Synchronized fun remove(id: Long) = save(_items.value.filterNot { it.id == id })

    private fun save(items: List<DownloadItem>) {
        val arr = JSONArray()
        items.forEach { item ->
            arr.put(JSONObject().apply {
                put("id", item.id)
                put("url", item.url)
                put("fileName", item.fileName)
                put("uri", item.uri)
                put("done", item.done)
                put("total", item.total)
                put("state", item.state.name)
                put("error", item.error)
                put("backend", item.backend.name)
                put("systemId", item.systemId)
                put("autoFileName", item.autoFileName)
                put("requestHeaders", JSONObject().apply {
                    item.requestHeaders.forEach { (name, value) -> put(name, value) }
                })
                put("expectedSha256", item.expectedSha256)
                put("retryCount", item.retryCount)
                put("etag", item.etag)
                put("lastModified", item.lastModified)
                put("sha256", item.sha256)
            })
        }
        prefs.edit().putString("items", arr.toString()).apply()
        _items.value = items
    }

    private fun load(): List<DownloadItem> = runCatching {
        val arr = JSONArray(prefs.getString("items", "[]"))
        buildList {
            for (i in 0 until arr.length()) {
                val o = arr.getJSONObject(i)
                val backend = runCatching {
                    DownloadBackend.valueOf(o.optString("backend", DownloadBackend.ENHANCED.name))
                }.getOrDefault(DownloadBackend.ENHANCED)
                val url = o.getString("url")
                val fileName = o.getString("fileName")
                add(
                    DownloadItem(
                        id = o.getLong("id"),
                        url = url,
                        fileName = fileName,
                        uri = o.optString("uri").takeIf { it.isNotBlank() && it != "null" },
                        done = o.optLong("done", 0L),
                        total = o.optLong("total", -1L),
                        state = runCatching { DownloadState.valueOf(o.optString("state")) }
                            .getOrDefault(DownloadState.PAUSED),
                        error = o.optString("error").takeIf { it.isNotBlank() && it != "null" },
                        backend = backend,
                        systemId = if (o.has("systemId") && !o.isNull("systemId")) o.optLong("systemId") else null,
                        autoFileName = if (o.has("autoFileName")) {
                            o.optBoolean("autoFileName", false)
                        } else {
                            looksAutoGenerated(url, fileName)
                        },
                        requestHeaders = jsonHeaders(o.optJSONObject("requestHeaders")),
                        expectedSha256 = o.optString("expectedSha256")
                            .takeIf { it.matches(Regex("(?i)[0-9a-f]{64}")) }
                            ?.lowercase(),
                        retryCount = o.optInt("retryCount", 0).coerceAtLeast(0),
                        etag = o.optString("etag").takeIf { it.isNotBlank() && it != "null" },
                        lastModified = o.optString("lastModified").takeIf { it.isNotBlank() && it != "null" },
                        sha256 = o.optString("sha256").takeIf { it.isNotBlank() && it != "null" },
                    ),
                )
            }
        }.map {
            if (it.backend == DownloadBackend.ENHANCED && it.state == DownloadState.RUNNING) {
                it.copy(state = DownloadState.PAUSED)
            } else {
                it
            }
        }
    }.getOrDefault(emptyList())

    companion object {
        @Volatile private var instance: DownloadStore? = null
        private val nextId = AtomicLong(System.currentTimeMillis())

        private fun looksAutoGenerated(url: String, fileName: String): Boolean {
            val derived = url.substringBefore('?').substringBefore('#').substringAfterLast('/').takeIf { it.isNotBlank() }
            return fileName == derived || (derived == null && fileName.startsWith("download-"))
        }

        private fun jsonHeaders(json: JSONObject?): Map<String, String> {
            if (json == null) return emptyMap()
            return buildMap {
                val keys = json.keys()
                while (keys.hasNext()) {
                    val name = keys.next()
                    val value = json.optString(name).takeIf { it.isNotBlank() } ?: continue
                    put(name, value)
                }
            }
        }

        fun get(context: Context): DownloadStore = instance ?: synchronized(this) {
            instance ?: DownloadStore(context).also { instance = it }
        }
    }
}
